
builders:
  testBuilder:
    import: "./lib/learnAnnotation.dart"
    builder_factories: ["testBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: root_package
    build_to: source